# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(verbose_name='about the game')),
                ('desc', models.TextField(verbose_name='description')),
                ('background', models.URLField(max_length=2048)),
                ('header', models.URLField(max_length=2048)),
                ('is_free', models.BooleanField()),
                ('metacritic_score', models.IntegerField(null=True)),
                ('metacritic_page', models.URLField(max_length=2048, null=True)),
                ('publishers', models.CharField(max_length=255)),
                ('recommendations', models.IntegerField(null=True)),
                ('coming_soon', models.BooleanField()),
                ('release_date', models.DateField(null=True)),
                ('required_age', models.IntegerField()),
                ('support_page', models.URLField(max_length=2048)),
                ('type', models.CharField(max_length=255)),
                ('website', models.URLField(max_length=2048, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('curator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(verbose_name='description')),
                ('avatar', models.URLField(max_length=2048)),
                ('page', models.URLField(max_length=2048)),
                ('followers', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField(verbose_name='description')),
                ('review_page', models.URLField(max_length=2048, verbose_name='full review')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.Application')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.Curator')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
