# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationUpdate',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='steam.Application')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuratorUpdate',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='steam.Curator')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
